name: Dev to Rudev Deploy
on: push
jobs:
    build:
        runns-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '16'
            - name: Install dependencies
              run: echo "Triggered from rudev"