name: MoDev Branch CI/CD with OIDC

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC authentication
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test -- --passWithNoTests
        continue-on-error: true
      
      - name: Build application
        run: npm run build
      
      # Configure AWS credentials using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam:::role/GitHubActionsOIDCRole-
          aws-region: us-east-2 
      
      # Install AWS Copilot CLI
      - name: Install AWS Copilot
        run: |
          curl -Lo copilot-cli https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
          chmod +x copilot-cli
          sudo mv copilot-cli /usr/local/bin/copilot
          copilot --version
      
      # List available applications and environments
      - name: List Copilot resources
        run: |
          echo "Listing available Copilot applications and environments..."
          copilot app ls || echo "No applications found"
          
      # Deploy using AWS Copilot
      - name: Deploy with AWS Copilot
        run: |
          echo "Deploying paymentmanagementmodev service to modev environment..."
          copilot svc deploy --app svcs --name paymentmanagementmodev --env modev
